apiVersion: apps/v1
kind: Deployment
metadata:
  name: oc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: oc-operator
  template:
    metadata:
      labels:
        name: oc-operator
    spec:
      serviceAccountName: oc-operator
      containers:
        - name: oc-operator
          # Replace this with the built image name
          image: haricotrouge/ocinterface:v0.0.1
          command:
          - oc-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "oc-operator"
